//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liberary_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookinfo
    {
        public string isbn { get; set; }
        public string title { get; set; }
        public int publisherid { get; set; }
        public System.DateTime publicationdate { get; set; }
        public int authorid { get; set; }
    }
}
