//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liberary_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserve
    {
        public int readerid { get; set; }
        public int bookid { get; set; }
        public System.DateTime date { get; set; }
    }
}
